extends RefCounted
class_name LocalizationRules

const DEFAULT_LANGUAGE: StringName = &"ru"

const TRANSLATIONS: Dictionary = {
	&"ru": {
		"ui.settings": "Настройки",
		"ui.skills": "Навыки",
		"ui.upgrades": "Улучшения",
		"ui.run": "Статистика",
		"ui.prestige": "Престиж",
		"ui.combat_text": "Боевой текст",
		"ui.show_damage": "Показывать урон",
		"ui.show_crit": "Показывать криты",
		"ui.show_miss": "Показывать промахи",
		"ui.show_hero_damage": "Урон по герою",
		"ui.show_hero_miss": "Промахи по герою",
		"ui.language": "Язык",
		"ui.enemy_summary": "Враги: Урон %s | Крит %s | Промах %s",
		"ui.hero_summary": "Герой: Урон %s | Промах %s",
		"ui.on": "ВКЛ",
		"ui.off": "ВЫКЛ",
		"run.title": "Статистика",
		"run.run_tab": "Забег",
		"run.stats_tab": "Статы",
		"run.overview": "Сводка",
		"run.wave_record": "Рекорд волны",
		"run.current_dps": "Текущий DPS",
		"run.echo_collected": "Эхо собрано",
		"run.echo_active": "Эхо активно",
		"run.echo": "Эхо",
		"run.active_bonus": "Активный бонус",
		"run.after_death_bonus": "Бонус после смерти",
		"run.hero_stats": "Статы героя (текущий забег)",
		"stat.damage": "Урон",
		"stat.attack_speed": "Скорость атаки",
		"stat.dps": "DPS",
		"stat.max_hp": "Макс HP",
		"stat.crit_chance": "Шанс крита",
		"stat.crit_mult": "Множ. крита",
		"stat.defense": "Защита",
		"stat.evasion": "Уклонение",
		"stat.accuracy": "Точность",
		"stat.move_speed": "Скорость движения",
		"abilities.permanent_slots": "постоянных слота навыков",
		"abilities.unlocks": "Открытия на мастерстве 1 / 3 / 5",
		"abilities.equipped": "Экипировано:",
		"abilities.slot": "Слот",
		"abilities.locked": "Закрыт",
		"abilities.locked_wave": "Закрыт до волны",
		"abilities.empty": "Пусто",
		"abilities.selected": "Выбрано",
		"abilities.state_equipped": "Экипировано",
		"abilities.state_available": "Доступно",
		"abilities.state_select_replace": "Выбери для замены",
	},
	&"en": {
		"ui.settings": "Settings",
		"ui.skills": "Skills",
		"ui.upgrades": "Upgrades",
		"ui.run": "Statistics",
		"ui.prestige": "Prestige",
		"ui.combat_text": "Combat Text",
		"ui.show_damage": "Show Damage",
		"ui.show_crit": "Show Crit",
		"ui.show_miss": "Show Miss",
		"ui.show_hero_damage": "Show Hero Damage",
		"ui.show_hero_miss": "Show Hero Miss",
		"ui.language": "Language",
		"ui.enemy_summary": "Enemy: Damage %s | Crit %s | Miss %s",
		"ui.hero_summary": "Hero: Damage %s | Miss %s",
		"ui.on": "ON",
		"ui.off": "OFF",
		"run.title": "Statistics",
		"run.run_tab": "Run",
		"run.stats_tab": "Stats",
		"run.overview": "Overview",
		"run.wave_record": "Wave Record",
		"run.current_dps": "Current DPS",
		"run.echo_collected": "Echo Collected",
		"run.echo_active": "Echo Active",
		"run.echo": "Echo",
		"run.active_bonus": "Active Bonus",
		"run.after_death_bonus": "After Death Bonus",
		"run.hero_stats": "Hero Stats (Current Run)",
		"stat.damage": "Damage",
		"stat.attack_speed": "Attack Speed",
		"stat.dps": "DPS",
		"stat.max_hp": "Max HP",
		"stat.crit_chance": "Crit Chance",
		"stat.crit_mult": "Crit Mult",
		"stat.defense": "Defense",
		"stat.evasion": "Evasion",
		"stat.accuracy": "Accuracy",
		"stat.move_speed": "Move Speed",
		"abilities.permanent_slots": "permanent skill slots",
		"abilities.unlocks": "Unlocks at mastery 1 / 3 / 5",
		"abilities.equipped": "Equipped:",
		"abilities.slot": "Slot",
		"abilities.locked": "Locked",
		"abilities.locked_wave": "Locked until wave",
		"abilities.empty": "Empty",
		"abilities.selected": "Selected",
		"abilities.state_equipped": "Equipped",
		"abilities.state_available": "Available",
		"abilities.state_select_replace": "Select To Replace",
	},
}

static func has_language(language_code: StringName) -> bool:
	return TRANSLATIONS.has(language_code)

static func translate(language_code: StringName, key: String) -> String:
	var lang_data: Dictionary = TRANSLATIONS.get(language_code, TRANSLATIONS[DEFAULT_LANGUAGE])
	return String(lang_data.get(key, key))
